nombre : LuckyWars
main: BellCranel\LuckyWars\LuckyWars
author: BellCranel
version: 2.0 Genisys PlanetaPacman
api: [3.0.0-ALPHA5]

commands:
    bc1:
        usage: /bc1 <leave-lw>
        description: LuckyWars-Commands
    lwstart:
        usage: /lwstart
        description: LuckyWars-Force start
